### ISSUE TITLE
Unable to import .xls, xlsx files from the menu using the file import option

### ISSUE THREAD

**Issue by boiledice** [electroly/sqlnotebook#12]
Unable to import .xls, xlsx files from the menu using the file import option. 
![image](https://cloud.githubusercontent.com/assets/4931736/25864818/adfddd72-34a5-11e7-854f-68e8ca669b4f.png)

Throws error that .xlsx isnt supported.

The command to import the xlsx from the script window is working.

**Comment by electroly** [comment]
The SQL commands to import from XLS have been implemented, but the GUI to import them has not been.  I need to finish the GUI for this.
