### ISSUE TITLE
notes color defaults to IE colors

### ISSUE THREAD

**Issue by 26labs** [electroly/sqlnotebook#14]
Seems to be taking from Internet Explorer color definitions.
Suggest would be better to use System colors as default.

**Comment by electroly** [comment]
Hi 26labs.  Are you referring to the "Dark" vs. "Light" app setting, or the other Windows color settings?  Most of the colors used in SQL Notebook are hard-coded.

**Comment by 26labs** [comment]
Hi Brian,
WHen the window displays it was taking the colors exactly from IE.  I had set that to use back background and green writing.
Closed sqlnotebook, changed my IE colors back to ‘system’ option, and reopened sqlnotebook and it was all ‘normal’. So i looked into the code and i see you are using IE for rendering of notes. So that is why the colors. Might be worth mentioning that in the ReadMe.  Its not a bug, just your design choice, so as long as users known about it then it wont be a surprise.

Thanks for responding.
Matt Taylor

**Comment by electroly** [comment]
This issue should no longer be applicable in version 1.0.0, which replaces the Internet Explorer-based notes with a custom Juypter-style notebook implementation.
