### ISSUE TITLE
Error when joining local and remote (SQL Server 2008 R2) tables 

### ISSUE THREAD

**Issue by mgilbert65** [electroly/sqlnotebook#19]
When executing a join where table aliased as "a" is a local table and the table aliased as "b" is a remote SQL Server 2008 R2 table, an error is displayed:

**SQL logic error or missing database**

However, when the remote table is deleted and them re-imported as a local table, the query executes successfully.

The query syntax did not change, only the table import method changed.

`select a.pro_number from ceva_csvfile a inner join ceva_cisdata b on a.pro_number = b.pro_number;`

Also, when the table was a remote table, I double checked that the table was in fact accessible, by double clicking the table name in the left pane of SQLNotebook (under tables heading) in order to view the data.

**Comment by electroly** [comment]
I have run into this issue with SQL Server 2008 as well.  There is definitely some kind of problem with SQL Notebook's support for 2008.  The connection gets into some kind of fault state and then future commands fail with the logic error.  I haven't found a reliable set of reproduction steps yet; can you make it happen every time, from a fresh launch of SQL Notebook?  We upgraded our server to 2016 and the problem went away, so I may have to try installing 2008 to diagnose this problem.

**Comment by mgilbert65** [comment]
I have rebooted and then launched a fresh instance of SQLNotebook with the same results.   Also, I tried both Windows authentication and standard security, but the results were the same.
