### ISSUE TITLE
Support multiple schemas in MS SQL Import dialog

### ISSUE THREAD

**Issue by vital3d** [electroly/sqlnotebook#2]
I have tables with the same name in various schemas, supporting schemas in the import MS SQL import dialog would allow a user to determine the correct table for the source.

![image](https://cloud.githubusercontent.com/assets/4139725/14788364/8171aea0-0ad5-11e6-99e8-328dad855828.png)

**Comment by electroly** [comment]
This will be fixed in the next version (0.6).  Thanks for reporting it!
