### ISSUE TITLE
Console not working for me

### ISSUE THREAD

**Issue by mreishus** [electroly/sqlnotebook#20]
No matter what I try, I can't get the console to do anything.  Am I doing something wrong?

![sqlnotebook_2017-05-11_08-22-43](https://cloud.githubusercontent.com/assets/937354/25951395/2b6e35f8-3623-11e7-98d9-77f58842a2ab.png)

Putting the same commands in a script window and pressing f5 does work, however.

**Comment by electroly** [comment]
Can you try editing the "Getting Started" note to see if you have any problems doing so?  Both the console and the notes editor are based on an embedded Internet Explorer browser; this will help me figure out if the problem is with that embedded browser, or somewhere else.

**Comment by mreishus** [comment]
![sqlnotebook_2017-05-16_13-02-16](https://cloud.githubusercontent.com/assets/937354/26120895/ee8bf8c8-3a37-11e7-90d4-c013f2d9e492.png)

Seems to work.

![sqlnotebook_2017-05-16_13-03-07](https://cloud.githubusercontent.com/assets/937354/26120923/0680f5d2-3a38-11e7-98f3-7ae02d5693ff.png)
