### ISSUE TITLE
ConsoleStates remaining even if Console is deleted.

### ISSUE THREAD

**Issue by stevenkl** [electroly/sqlnotebook#31]
ConsoleStates remaining even if Console is deleted, so also the used variables are available.

**Comment by electroly** [comment]
Can you explain further what you mean?  Can you write up a set of reproduction steps for this bug?

**Comment by Churanos** [comment]
- Open a console in your notebook, name is `Console1`
- Declare a variable `Declare $name = 'Churanos'`
- Save notebook
- delete `Console1` and save
- open a new console, name is again `Console1`
- do `print $name`, it works even the variable was not declared

In the `notebook.json` file the ConsoleState remains with the given name. If i open a new console the stored State are used.

This happens also if i rename a console.
Here an example:
- Open the attached Notebook [test.zip](https://github.com/electroly/sqlnotebook/files/1796067/test.zip) (Rename it to test.sqlnb)
- create a new console, name should `Console1`
- enter directly `print $username`, you see the value even you never declared the variable

I hope this illustrates it.

**Comment by electroly** [comment]
This issue should no longer be applicable in version 1.0.0, since it offers a single universal console instead of adding consoles as items to the notebook.
