### ISSUE TITLE
SPLIT() is not working properly

### ISSUE THREAD

**Issue by libinks10** [electroly/sqlnotebook#34]
Please try below code :

DECLARE @data = SPLIT('AAA|BBB|CCC', '|', 1);
select @data

Expecting the result as 'BBB' as per your documentation where we are getting 'System.Byte[]'

**Comment by electroly** [comment]
Hi, thank you for the bug report!  I can reproduce this problem as well.  It looks like it is returning an array with ('AAA', 'BBB', 'CCC') instead of returning the result at index 1.  I will fix this.
