### ISSUE TITLE
Error running installed and portable version

### ISSUE THREAD

**Issue by yaba** [electroly/sqlnotebook#42]
In a machine with Windows 7, SP1, x64 throws the following error:
Missing "api-ms-win-core-winrt-l1-1-0.dll"

**Comment by electroly** [comment]
Hi @yana, thank you for the report. I will investigate this error.

**Comment by electroly** [comment]
Thanks again for this report. I have released version 1.0.1 which should fix this issue. Take note of the special Windows 7 requirements linked from the release page; you must install hotfix KB2533623 if you don't have it already. Please let me know if this new version fixes the issue for you.

**Comment by yaba** [comment]
Thanks @electroly, it's working now.
