### ISSUE TITLE
Column datatype assignment

### ISSUE THREAD

**Issue by ohmh** [electroly/sqlnotebook#45]
It would be great if the datatype of multiple columns can be changed in bulk instead of clicking on each column and changing the  datatype when importing csv files for that becomes very tedious with tables of many columns

**Comment by electroly** [comment]
Hi @ohmh, that is a good idea. I have some ideas for how this could be implemented. I've also considered having it auto-detect the initial data types (while still allowing you to change them) but I'm unsure whether that's desirable behavior.

**Comment by ohmh** [comment]
Automation would be great but also the ability to manually configure things in an efficient manner is crucial.

**Comment by electroly** [comment]
This issue should now be fixed in [version 1.2.0](https://github.com/electroly/sqlnotebook/releases/tag/v1.2.0). Please give it a try. Thanks!
