### ISSUE TITLE
issue when press ctrl+s shortcut multiple times

### ISSUE THREAD

**Issue by kaala** [electroly/sqlnotebook#52]
I usually use shortcut to save notebook, If I press ctrl+s 2 times, there will be DC3 in scripts
I guess you control the menu item to not allow save multiple times, but shortcuts is not.

![图片](https://user-images.githubusercontent.com/246542/200995217-c08256d3-b2d0-405a-8f54-21bdfb4fe1aa.png)

**Comment by electroly** [comment]
This issue has been fixed in version 1.2.1. Thank you for reporting it.
